### ISSUE TITLE
Is there anything we can do to get this into serde_json?

### ISSUE THREAD

**Issue by rw** [Alexhuszagh/minimal-lexical#1]
Following up from https://github.com/serde-rs/json/issues/536, I'm like to help get this merged into serde_json. Is there anything we can do to help?

(My application has a hard requirement to correctly parse f32 and f64 values from JSON.)

**Comment by rw** [comment]
@Alexhuszagh bump! Feel free to email me if you have a moment.

**Comment by Alexhuszagh** [comment]
Hi @rw, sorry, I had to take a break from open source work for mental health reasons. Thanks for understanding, I'm glad to see it's been integrated into serde-json as a private fork. Also, thanks for all the suggestions for better feature development in lexical. I'm back to maintaining my open source projects, and doing much better.
