### ISSUE TITLE
3-clause BSD license needs to be reproduced in this repo

### ISSUE THREAD

**Issue by str4d** [Alexhuszagh/minimal-lexical#5]
https://github.com/Alexhuszagh/minimal-lexical/blob/f6399813f02b7a55a875672c284ef3f69c2a34d6/src/bellerophon.rs#L13-L15

Per the terms of the Go license, its license file needs to be reproduced in this repository alongside the source code: https://github.com/golang/go/blob/b10849fbb97a2244c086991b4623ae9f32c212d0/LICENSE

This issue came up because I want to use `nom 7` in Fuchsia OS (which requires satisfying Google's open-source license requirements), and `minimal-lexical 0.1.3` is a dependency of `nom 7`. It would be great if a `minimal-lexical 0.1.4` could be released that includes the missing `LICENSE` file. I can open a PR to this effect if that would help.

**Comment by Alexhuszagh** [comment]
For sure, a PR would be more than welcome. This code is only used if the `compact` feature is enabled, but this was definitely an oversight on my part. I'll add a section in the README after a PR is merged to that effect.

**Comment by Alexhuszagh** [comment]
This might also be necessary in the original library this was ported from ([lexical](https://github.com/Alexhuszagh/rust-lexical#license)), which credits all dependent libraries and links their source and licenses, doesn't reproduce the licenses in full. Thanks.

**Comment by Alexhuszagh** [comment]
Both versions 0.2.1 and 0.1.4 have been published to crates.io.
